# Generated by Django 2.1.1 on 2018-10-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_sex', models.BooleanField()),
                ('user_age', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('gun_control', models.IntegerField()),
                ('abortion', models.IntegerField()),
                ('immigration', models.IntegerField()),
                ('drugs', models.IntegerField()),
                ('healthcare', models.IntegerField()),
                ('latest', models.IntegerField()),
            ],
        ),
    ]
