# Generated by Django 2.1.1 on 2018-10-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_meetup_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_age',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_sex',
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
